# Generated by Django 4.1.7 on 2023-03-28 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Characters",
            new_name="Character",
        ),
    ]
