# Generated by Django 4.1.7 on 2023-03-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0002_rename_characters_character"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Female", "Female"),
                    ("Male", "Male"),
                    ("Genderless", "Genderless"),
                    ("Unknown", "Unknown"),
                ],
                max_length=50,
            ),
        ),
    ]
